### ISSUE TITLE
master: sync release 1.1 branch

### ISSUE THREAD

**Issue by silentdai** [istio/proxy#2218]
- [ ] Update istio/api for 1.1rc5 (#2153)
a5d5a46

- [ ] Fixes environment-dependent failures in MixerFaultTest (#2144)
9d52640

- [ ] Update API and import envoyproxy/envoy#6263 (#2157)  …
55c8096

- [ ] update envoy to latest (#2158)  …
5a9945b
 
- [ ] release 1.1: Update envoy to enable path normalization (#2166)  …
bf8b9cd

- [ ] Sync istio/api for 1.1.3 (#2170)
a169a0c

- [ ] Updating API sha for proxy. (#2181)  …
73fa9b1

- [ ] Retrieve tracing header from request headers during report (#2182)  …
56242cd

**Comment by silentdai** [comment]
Thank @crazyxy for taking this!
